#!/bin/sh
make glass-test-1
make glass-test-2
make glass-test-3
make glass-test-4
make laser-test-1
make laser-test-2
make laser-test-3
make laser-test-4
make laser-test-5
make laser-test-6
make milloneup-test-1
make milloneup-test-2
make milloneup-test-3
make simple_laser-test-1
make simple_laser-test-2
make simple_laser-test-3
make tq-test-1
make tq-test-2
make tq-test-3
make tq-test-4
make tq-test-5
make tq-test-6
make tq-test-7
make tq-test-8
make tq-test-9
make traffic3cars-test-1
make traffic3cars-test-2
make traffic3cars-test-3
make traffic3cars-test-4
make traffic3cars-test-5
make traffic3cars-test-6
make turn-test-1
make turn-test-2
make turn-test-3
make turntwo-test-1
make turntwo-test-2
make turntwo-test-3
make turntwo-test-4
make turntwo-test-5
make turntwo-test-6
make vanderpol-test-1
